# see: https://golangci-lint.run/usage/configuration/

run:
  tests: true

linters:
  enable:
    - revive
    # - godox # Enable when all TODO/FIXME resolved
    - goimports
    - gosec
    - noctx
    - nolintlint
    - prealloc
    - misspell

issues:
  exclude-use-default: false
  exclude:
    - "G304: Potential file inclusion via variable"
    - "G306: Expect WriteFile permissions to be 0600 or less"
    - "G402: TLS MinVersion too low"
    - "G402: TLS InsecureSkipVerify set true"
    - "exported (type|method|function|const|var) (.+) should have comment or be unexported"
    - "package-comments: should have a package comment"

  exclude-rules:
    - path: _test\.go
      linters: [ noctx ]
    - path: _test\.go
      text: "Error return value of `(.+).Close` is not checked"
    - path: _test\.go
      text: "G404:" # G404: Use of weak random number generator
    - path: testutil/
      text: "G404:" # G404: Use of weak random number generator

    - path: router/routetable/routes.go
      text: "G404:" # G404: Use of weak random number generator
