# see: https://golangci-lint.run/usage/configuration/

run:
  tests: true

issues:
  exclude-use-default: false

linters:
  enable:
    - revive
    # - godox # Enable when all TODO/FIXME resolved
    - goimports
    - gosec
    - noctx
    - nolintlint
    - prealloc
    - misspell

issues:
  exclude:
    - "G402: TLS MinVersion too low"
    - "G402: TLS InsecureSkipVerify set true"
    - "G306: Expect WriteFile permissions to be 0600 or less"
    - "exported (type|method|function) (.+) should have comment or be unexported"
